spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  kafka:
    bootstrap-servers: git push:9092
    topic:
      userRegistered: USER_REGISTERED_TOPIC
  mail:
    host: smtp.gmail.com
    port: 587
    username: sudhavuppalapati@gmail.com
    password: Sudha123
    properties.mail.smtp:
      auth: true
      starttls.enable: true
security:
  basic:
    enabled: false